### ISSUE TITLE
Eagle CAD Difficulties

### ISSUE THREAD

**Issue by Reyna-5970** [Agile-and-Adaptive-Robotics/Inverted_Pendulum#10]
I'm having some trouble with the Eagle CAD board layout for the custom arduino shield we're designing. When I update footprints and devices, it doesn't seem to transfer over the the PCB layout. Do you know why this would be?

Also I occasionally receive an error about a broken link between the schematic and board after closing the board file. I save the board and attempt to close it through the menu, but it still seems to happen. I suspect this might be the cause for the issue above, but am not sure how to address it.

**Comment by Scharzenberger** [comment]
Hey Reyna,

Sorry for being slow about getting back to you.  I am not 100% confident, but it sounds like your schematic and board files may have gotten out of sync.  This can happen if you only have one of them open while you edit the other (seems silly, but you need to have both open at the same time) or if you rename / change the path associated with either file.  Normally, whenever you edit something on the schematic (i.e., add a component, change the wiring, delete a component, etc.) these changes are automatically propagated to the board, but once you are out of sync, it starts having problems.

I was just googling about the out of sync issue and I don't see a ton that is very helpful.  It sounds like if they are out of sync, you have to go back and manually change the files to agree and then hopefully they will start updating together again.

You have probably already saw it, but there is a short discussion [here](https://www.element14.com/community/thread/43500/l/board-inconsistency-how-to-update?displayFullThread=true).

Sorry I don't have more advise.  I would just search up "eagle cad sync schematic and board" and see if you get anything helpful.

Let me know how it goes.
