### ISSUE TITLE
Recent pull-request restored old version of CAD files

### ISSUE THREAD

**Issue by Reyna-5970** [Agile-and-Adaptive-Robotics/Inverted_Pendulum#22]
Molly was working on the main assembly but within a branch that was not fully updated at the time (I believe due to github errors with committing to a branch that had already been merged). The branch in question is from pull request #20.

However, in the branch minorFootAdjustments-ReynaAy-feat from pull request #17, I had made quite a few small edits to the foot assembly, which now appear to be overwritten by the most recent branch merging. Is there a way to recover this version of just the foot assembly (at the time, I did not edit the overall assembly nor the tibia assembly)?

**Comment by jakechung42** [comment]
I haven't deleted the branch minorFootAdjustments-ReynaAy-feat, so you should be able to get that file in that branch.

- In GitHub Desktop, navigate to that branch and copy the foot assembly file that you want.
- Store it in a temporary location outside of the GitHub directory.
- Switch to the branch that you are working on where you would want to foot assembly file.
- Bring the foot assembly file from the temporary location and paste it in the GitHub directory. 

Try that, I think that shouldn't cause any conflict.

**Comment by Reyna-5970** [comment]
Seemed to work, thanks!
